---
title: "Vector Benchmark"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE}
library(ggplot2)
```

```{r collapse=TRUE}
cat(paste("R", getRversion(), "\n"))
cat(paste("sf", packageVersion("sf"), "\n"))
cat(paste("terra", packageVersion("terra"), "\n"))
cat(paste("s2", packageVersion("s2"), "\n"))
cat(paste("geos", packageVersion("geos")))
```

```{r collapse=TRUE}
# check it manually
cat("Python 3.13.7", "\n")
cat("geopandas 1.1.1")
```

```{r collapse=TRUE}
# check it manually
cat("Julia 1.11.7", "\n")
cat("GeometryOps 0.1.26")
```

```{r}
files = list.files("results", full.names = TRUE)
df = lapply(files, read.csv2)
df = do.call(rbind, lapply(files, read.csv2,
                           colClasses = c("factor", "factor", "numeric")))
```

## Sampling points
**100 000 points**

```{r sample}
df_agg = df[df$task == "sample", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Transform CRS

```{r transform}
df_agg = df[df$task == "transform", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Geometries intersects

```{r intersects}
df_agg = df[df$task == "intersects", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.4) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.4) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Load geopackage

```{r load}
df_agg = df[df$task == "load", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Write geopackage

```{r write}
df_agg = df[df$task == "write", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Creating buffers

```{r buffer}
df_agg = df[df$task == "buffer", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Distance
**4000 points**

```{r distance}
df_agg = df[df$task == "distance", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```


```{r final-plot, eval=FALSE}
df_agg = aggregate(time ~ task + package, df, median)

# language as a new variable
df_agg$lang = ifelse(df_agg$package %in% "geopandas", "Python", NA)
df_agg$lang = ifelse(df_agg$package %in% "geometryops", "Julia", df_agg$lang)
df_agg$lang[is.na(df_agg$lang)] = "R"
df_agg$lang = as.factor(df_agg$lang)

# capitalize task names
levels(df_agg$task) = tools::toTitleCase(levels(df_agg$task))

# drop slower funs from same packages
df_agg = df_agg[!df_agg$package == "sf-transform", ]

# return only first part of string
pkg_name = strsplit(as.character(df_agg$package), "-")
df_agg$package = sapply(pkg_name, "[[", 1)

p = ggplot(df_agg, aes(x = package, y = time)) +
  geom_point(aes(shape = lang, color = package), size = 2) +
  facet_wrap(vars(task), scales = "free_y") +
  # override circles with diamonds in legend
  guides(colour = guide_legend(override.aes = list(shape = 18, size = 3.5))) +
  labs(title = "Benchmark vector operations",
       caption = "https://github.com/kadyb/vector-benchmark",
       color = "Package", shape = "Language") +
  scale_color_brewer(palette = "Set1") +
  ylab("Time [s]") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.caption.position = "plot",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(colour = "black")
        )
p
```

```{r}
ggsave("comparison.png", p, width = 750, height = 450, units = "px", scale = 2.5)
```

```{r}
timings = aggregate(time ~ task + package, df, median)
colnames(timings)[3] = "median"
timings$median = round(timings$median, 2)
write.csv(timings, "timings.csv", row.names = FALSE, quote = FALSE)
```
